# **Tarea de Numpy**

Este notebook es el de los ejercicios >:)

In [1]:
import numpy as np

# Probando si si jala el numpy
my_arreglow = np.array([1, 2, 3, 4, 5])

print(my_arreglow)
print(np.mean(my_arreglow))


[1 2 3 4 5]
3.0


## Ejercicios de refuerzo

### **Ejercicio 1 - Crear un array de ceros:**
Crea un array de tamaño (3, 4) lleno de ceros.

In [8]:
# Solución (:
arr = np.zeros((3,4))
print("Array lleno de ceros:\n", arr)


Array lleno de ceros:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### **Ejercicio 2-  Suma de elementos:**
   Dado el array [1, 2, 3, 4, 5], calcula la suma de todos sus elementos usando NumPy.

In [12]:
# Solucion :)
arr = np.array([1,2,3,4,5])
array_sum = np.sum(arr)

print("Suma del array dado: ", array_sum)


Suma del array dado:  15


### **Ejercicio 3 - Encontrar el máximo y mínimo:**
Dado el array [10, 20, 30, 40, 50], encuentra el valor máximo y mínimo.

In [18]:
array = np.array([10, 20, 30, 40, 50])

# Solución:)
max = np.max(array)
min = np.min(array)
print("Valor máximo:", max, "\nValor mínimo:", min)



Valor máximo: 50 
Valor mínimo: 10


### **Ejercicio 4 - Encontrar el máximo y mínimo:**
 Dado el array [10, 20, 30, 40, 50], encuentra el valor máximo y mínimo.


In [19]:
# Solución:)
array = np.array([10, 20, 30, 40, 50])

max = np.max(array)
min = np.min(array)
print("Valor máximo:", max, "\nValor mínimo:", min)

Valor máximo: 50 
Valor mínimo: 10


### **Ejercicio 5 - Generar números aleatorios:**
  Genera un array de 5 números aleatorios entre 0 y 1.

In [22]:
# Solución:)
random_array = np.random.random(5)
print(random_array)


[0.53810441 0.5477021  0.46937033 0.22173551 0.12257581]


### **Ejercicio 6 - Promedio de un array:**
Dado el array [5, 10, 15, 20, 25], calcula su promedio usando NumPy.

In [25]:
#Solucion:)
arr = np.array([5,10,15,20,25])
print(arr)

prom = np.average(arr)
print("Promedio:",prom)


[ 5 10 15 20 25]
Promedio: 15.0


### **Ejercicio 7 - Concatenar dos arrays**
Dados los arrays A = [1, 2, 3] y B = [4, 5, 6], concaténalos en un solo array.

In [33]:
#Solucion:)
arr1 = np.array([1,2,3])
print("Array A: ",arr1)
arr2 = np.array([4,5,6])
print("Array B: ",arr2)

mix = np.concatenate((arr1, arr2))
print("Array combinado: ",mix)

Array A:  [1 2 3]
Array B:  [4 5 6]
Array combinado:  [1 2 3 4 5 6]


### **Ejercicio 8 - Reshape de un Array**
Dado el array [1, 2, 3, 4, 5, 6], cámbialo a una matriz de 2x3.

In [37]:
#Solución:)
arr = np.array([1,2,3,4,5,6])
print("Array:",arr)

new = np.reshape(arr, (2,3))
print("Matriz:\n",new)

Array: [1 2 3 4 5 6]
Matriz:
 [[1 2 3]
 [4 5 6]]


### **Ejercicio 9 - Producto punto (dot product):**
Dados dos arrays A = [1, 2, 3] y B = [4, 5, 6], calcula su producto punto

In [42]:
#Solución:)
A = np.array([1,2,3])
B = np.array([4,5,6])

dot = np.dot(A,B)
print("Producto punto:",dot)

Producto punto: 32


### **Ejercicio 10 - Reorganizar un array:**
Dado el array [1, 2, 3, 4, 5, 6, 7, 8, 9, 10], conviértelo en una matriz (2, 5).

In [39]:
#Solución:)
arr = np.array([1,2,3,4,5,6,7,8,9,10])
print("Array:",arr)

change = np.reshape(arr, (2,5))
print("Matriz (2,5)\n",change)


Array: [ 1  2  3  4  5  6  7  8  9 10]
Matriz (2,5)
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


### **Ejercicio extra - Encontrar el *k*-ésimo elemento más pequeño en un array**
Dado arr = np.array([9, 3, 6, 2, 1, 7]), encuentra el 3er elemento más pequeño sin ordenar el array completo.

**Pista solución 1**: Se puede hacer con un método de Numpy

**Pista solución 2**: El código se hace más complicado, pero se puede resolver con ciclos iterativos.

In [45]:
#Solucion :o
arr = np.array([9, 3, 6, 2, 1, 7])

# partition mueve los k+1 menores elementos al principio del arreglo, sin importar el orden entre ellos
k=2
part = np.partition(arr, k)
tercer_menor=part[k]

print(tercer_menor)



3


## **Ejercicios aplicados**

### **Ejercicio: Cálculo de ROI (Retorno de Inversión)**
Dadas las inversiones ([1000, 1500, 2000]) y sus retornos ([1200, 1650, 1800]), calcula el ROI porcentual para cada caso.

*(Fórmula: ROI = (retorno - inversión) / inversión * 100)*

In [46]:
# Solucion del ROIROIROIROIORIORI
inversiones = np.array([1000,1500,2000])
retornos = np.array([1200,1650,1800])

roi = ((retornos-inversiones)/inversiones)*100
print("ROI:", roi)


ROI: [ 20.  10. -10.]


### **Ejercicio: Normalización de Datos**
Tienes un dataset de precios de productos (en USD): [250, 320, 150, 500, 210]. Normaliza los valores al rango [0, 1] para compararlos en una escala común.

**Formulita de la normalización**: (x - min) / (max - min): Para una escala valores entre 0 y 1.

In [51]:
precios = np.array([250,320,150,500,210])
min = np.min(precios)
max = np.max(precios)

normalizacion = (precios - min)/(max - min)
print("Normalizados:",normalizacion)

Normalizados: [0.28571429 0.48571429 0.         1.         0.17142857]


### **Ejercicio: Filtrado de Datos**
En un array de ventas diarias ([1200, 0, 750, 2400, 0, 1800]), reemplaza los ceros (días sin ventas) por el promedio de los días con ventas.

In [65]:
ventasDiarias = np.array([1200,0,750,2400,0,1800])

promedioVentas = np.average([v for v in ventasDiarias if v != 0])
print("Promedio ventas:",promedioVentas)

# Recorro usando índices con range(len(...)), me permite acceder al índice
for i in range(len(ventasDiarias)):
    if ventasDiarias[i] == 0:
        ventasDiarias[i] = promedioVentas

print("Array modificado:",ventasDiarias)

Promedio ventas: 1537.5
Array modificado: [1200 1537  750 2400 1537 1800]


### **Ejercicio - Análisis de Presión Arterial**
Tenemos un dataset de mediciones de presión arterial sistólica (mmHg) de 10 pacientes:
[120, 135, 140, 118, 150, 130, 160, 125, 142, 128].

Calculen:
- Media y desviación estándar.
- Identifiquen valores fuera del rango normal (90–140 mmHg).

In [69]:
presiones = np.array([120,135,140,118,150,130,160,125,142,128])

print("Media =", np.mean(presiones))
print("Desv estándar =", np.std(presiones))

for x in range(len(presiones)):
    if presiones[x]<90 or presiones[x]>140:
        print("Valor fuera del rango normal: ", presiones[x])


Media = 134.8
Desv estándar = 12.69488085804668
Valor fuera del rango normal:  150
Valor fuera del rango normal:  160
Valor fuera del rango normal:  142


### **Ejercicio - Cálculo del PIB per Cápita**
Dados el PIB (en millones de USD) [500, 320, 700, 450] y la población (en millones) [10, 8, 12, 9] de 4 países, calculen el PIB per cápita y determinen el país con el mayor valor.

In [75]:
PIB = np.array([500,320,700,450]) # millones usd
poblacion = np.array([10,8,12,9]) # millones

pib_per_capita = PIB / poblacion
print("PIB per cápita:",pib_per_capita)

mayor_pib = np.max(pib_per_capita)
print("Valor del país con mayor pib per cápita: ", mayor_pib, "mil usd per cápita")

PIB per cápita: [50.         40.         58.33333333 50.        ]
Valor del país con mayor pib per cápita:  58.333333333333336 mil usd per cápita


### **Ejercicio - Sistema de Drops (Probabilidades)**
En un videojuego RPG, los enemigos al ser vencidos, pueden dropear (soltar):
- 0 = Nada (50%).
- 1 = Poción (30%).
- 2 = Arma (15%).
- 3 = Artefacto (5%).

Simula 100 drops y cuenta cuántos artefactos se obtuvieron.

*Ejemplo de salida*:

```
Artifactos obtenidos: 3
```



In [ ]:
#Posibles drops
drops = [0,1,2,3]
probabilidades = [0.5, 0.3, 0.15, 0.05]

#Simulacion
# np.random.choice(listaOPciones, size=N, probabilidades)
sim = np.random.choice(drops, size=100, p=probabilidades)

cantidad_artefactos = np.count_nonzero(sim == 3)

print("Artefactos obtenidos:", cantidad_artefactos)

Artefactos obtenidos: 4
